development:
  adapter: redis
  url: redis://localhost:6379  

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV["REDIS_URL"] || "redis://localhost:6379" %>
  channel_prefix: in_a_nutshell_production
